from .buzzer import hardware_buzzer
from .capabilities import hardware_capabilities
from .communicator import hardware_communicator
from .display import hardware_display
from .i2c import hardware_i2c
from .i2s import hardware_i2s
from .joystick import hardware_joystick
from .leds import hardware_leds
from .onboard_buttons import hardware_onboard_buttons
from .pinout import hardware_pinout
from .sao import hardware_sao
from .spi import hardware_spi
from .uart import hardware_uart
